# This is a python coding tutorial by Snowy. 

import time
print("Hello, would you please insert your name?")
name = input()
print("hello", name+"!")
time.sleep(1)
print("how does that happen? how do i know your name is", name+"?")
print("------------------------------------------------------------")
print("this is one of the most important things when it comes to coding. these are called, variables.")
print("enter a name for your variable!")
var1 = input()
print(var1, "is a good choice", name+"!")
time.sleep(2)
print("now time to do something special. give it a value!")
time.sleep(1)
print("give", var1, "a value!")
var2 = input()
time.sleep(2)
print("So now", var1, "has a value of", var2)
time.sleep(2)
print("well.. what else can you do with it? make a calculator of course!")
print("-----------------------------------------------------------------")
print("First we will start out with 2 variables, a and b. for this we will be making an addition calculator. we can recieve input with `input()` so we can gather the numbers.")
print("A")
a = int(input())
print("B")
b = int(input())
print("good. you put your values like so:")
print("a =", a)
print("b =", b)
time.sleep(2)
print("using the variables, you can now use the formula `a + b` to find the answer.")
time.sleep(3)
print("so this is what your code produced:")
time.sleep(1)
print(a+b)
time.sleep(3)
print("as you can see", name, "python can be used in so many ways. this is just a small example.")
time.sleep(2)
print("")
print("-----------------------------------------------------------------------------------------")
print("© 2023 Snowy | All Rights Reserved")
